### ISSUE TITLE
Write minimal documentation

### ISSUE THREAD

**Issue by skjerns** [target/matrixprofile-ts#20]
Great to see a python implementation of MP, I've always wanted to play around in Python but never got to it.

I would appreciate to include some minimal function description, maybe in form of docstrings e.g.
```python
def stomp(tsA,m,tsB=None):
"""
:param tsA: ...
:param m: length of...
"""
```

At this moment it's not really clear to me what each parameter does without re-watching the introduction video or infering this from some paper.

**Comment by vanbenschoten** [comment]
Thanks for the suggestion! We'll take another look at the documentation to see if it can be made clearer.

**Comment by vanbenschoten** [comment]
The real issue is that the topline matrixprofile.py functions have no documentation, but the lower levels (distanceprofile.py, utils.py, etc) do. I'll go ahead and add some more info to matrixprofile.py.

**Comment by vanbenschoten** [comment]
@skjerns I've added some more detail for the functions. Let me know if this helps!

**Comment by skjerns** [comment]
great work, thanks!
