### ISSUE TITLE
Readme is a bit missleading

### ISSUE THREAD

**Issue by zippeurfou** [target/matrixprofile-ts#21]
Hi,
Very interesting concept thanks for coding it and sharing it.
In the readme, you mention:
> We can introduce an anomaly to the end of the time series and use STAMPI to detect it
And then you conclude
> The Matrix Profile has spiked in value, highlighting the (potential) presence of a new behavior

I am a bit puzzled by this.. Yes the matrix profile has spiked but so did the data. I do not see in this example the additional value of STAMPI.
Overall I am a bit confused about how to interpret the data. Especially if you'd like to do it in an automatic way for an anomaly detection.
Here is a picture taking the example with some questions..
<img width="908" alt="b34f5467c762150b8bf5c0404e4a6551 _image 2019-01-11 at 12 01 40 pm" src="https://user-images.githubusercontent.com/4520383/51030457-c6bd8700-1599-11e9-9811-b20c54786264.png">
The first one, the number seems pretty high, so this mean that the z-norm euclidian distance is high (correct me if I am wrong). However, I could argue that there was just a changepoint and this is the normal "new behavior" (ie. there was an earthquake at the beginning of the data and then it went off).
Going into this logic, I would interpret the black square more as outliers than "normal" but in this the MP have values close to 0 which would mean (if I understand correctly) that it should not be seen as outliers.
Finally at the end I am unsure why I see an initial spike or the data going back to 0.
I am sure this come from my lack of understanding of the MP but it might be nice to add a more detailed description of this chart as well as a function or an heuristic in the readme to automatically detect outliers using MP.
Best,

**Comment by aouyang1** [comment]
The green box actually is not an outlier due to how the data was generated. The noise in this section is mostly identical to the noise after the small sinusoidal pulse. This results in a lower matrix profile value whereas a higher value should be expected if the noise sections were not correlated. 

In the black box, the small sinusoidal pulse is not an outlier because the pattern is exhibited more than once as seen in the second pulse. The low points in the matrix profile there will indicate that the nearest motif are the pulses them selves.

The yellow box indicates a discord as well which is a noisy section entering the triangular wave region which is not present anywhere else in the time series signal. Once the 32 sample window enters into the triangular section we notice the matrix profile significantly drops.

**Comment by zippeurfou** [comment]
Thanks Austin for your answer.
I guess I am still a bit confused on how to interpret the value then and the conclusion is that I should do a bit more reading. I have to admit I only quickly skipped through the paper. I was thinking that in the green boxes having MP ~3 meant it was interpreted as outliers but this must be incorrect.
Side note, I think it would be nice to share the csv or give a downloadable link to it for anyone to be able reproduce it.

**Comment by aouyang1** [comment]
the outlier detection from my experience can be a bit tricky with matrix profiles. The clear ones have a shape that's distinctly mountain-like and have just one in the whole matrix profile. Multiple spikes may indicate that those spikes are also anomalies, but may need further assessment on them.

I can probably whip together something quick for creating the signal in python and get a pull request sent out. If you're interested in how the signal was generated right now, you can take a look at https://github.com/aouyang1/go-matrixprofile/blob/master/matrixprofile/example_caseStudy_test.go#L171.

**Comment by zippeurfou** [comment]
Thanks again!
> Multiple spikes may indicate that those spikes are also anomalies, but may need further assessment on them.

Thanks, for the details. It was kind of my fear in the first post. If you need to do further assessment on them then you can't really use this to automatically detect anomaly (at least by itself) which kind of go against the description of the package:

> A Python library for detecting patterns and **anomalies** in massive datasets using the Matrix Profile

Thanks for sharing the code to generate the data.

**Comment by aouyang1** [comment]
I think a big part is to define what an anomaly is in the matrix profile sense. To me it's a pattern that is present only once in the observed time frame. A second occurrence would then make it a motif.

**Comment by vanbenschoten** [comment]
@zippeurfou apologies! For some reason I'm not receiving notifications when issues are opened. Right now this repo focuses on calculating the raw Matrix Profile; you're right in that there's usually additional steps to build a complete anomaly detection system (as there is for any algorithm). In this case the top three spikes all represent changepoints in the data behavior, so really the raw Matrix Profile is best for detecting anomalous patterns (as called out by Austin). However, you can still do things like normalize Matrix Profile values by time window (e.g. 12-12:05PM every day) to account for things like background noise. You can find some other ideas in the Hacker News thread discussing matrixprofile-ts here: https://news.ycombinator.com/item?id=18824315.

**Comment by zippeurfou** [comment]
Thanks @aouyang1 @vanbenschoten it all makes sense to me  now:).

**Comment by vanbenschoten** [comment]
Closing this issue for now, but feel free to re-open if more discussion is helpful.

**Comment by tylerwmarrs** [comment]
I think that the biggest point of confusion is this line:

"We can introduce an anomaly to the end of the time series and use STAMPI to detect it "

Stampi does not detect the anomaly, but it appends new data regardless of the data being anomalous. Maybe clarification on what Stampi is doing is needed.

**Comment by hmcoservit** [comment]
Is there an example of using STAMPI?
