### ISSUE TITLE
Proposal For Discord Discovery - Jupyter Example

### ISSUE THREAD

**Issue by tylerwmarrs** [target/matrixprofile-ts#27]
I wrote a blog post about this library and how to use it on a NAB dataset to detect discords. I can rewrite the notebook and contribute it to the examples section if you want. You can read the post here. http://tylermarrs.com/posts/anomaly-detection-matrix-profile-discords/

**Comment by vanbenschoten** [comment]
Closing as relevant PR has been merged.
