### ISSUE TITLE
[ rawdata.csv in Matrix_Profile_Tutorial.ipynb ] is missing

### ISSUE THREAD

**Issue by wooheaven** [target/matrixprofile-ts#34]
2nd Cell of [ matrixprofile-ts/docs/examples/Matrix_Profile_Tutorial.ipynb ]
rawdata.csv is missing

```{text}
Overview
This notebook demonstrates how to calculate and update the Matrix Profile for a sample dataset 
(this is the same example signal used in https://github.com/aouyang1/go-matrixprofile)
```

Would you guide more detail steps for generate ? ot Add the rawdata.csv ?

It's nonsense that I have to spent time in order to get the rawdata.csv file by clone/build/run go-matrixprofile.

I think that this matrixprofile is independent of the go-matrixprofile in code level.
So there is no rule for use same input data as gp-matrixprofile. It's up to users.
Just it is a suggestion of yours.
And because of your suggestion, 2nd Cell of [ matrixprofile-ts/docs/examples/Matrix_Profile_Tutorial.ipynb ] has FileNotFoundError.
Do you agree with this nonsense status ?

--------------------------------------------

I upload the rawdata.csv
[rawdata.txt](https://github.com/target/matrixprofile-ts/files/2816392/rawdata.txt)
(Github doesn't support csv. Download it and then read as rawdata.txt not rawdata.csv

**Comment by vanbenschoten** [comment]
Yeah, the CSV should definitely be there (we don't want folks to have to run the golang version every time). I'll upload a copy of the file later today.

Thanks for the heads-up!

**Comment by vanbenschoten** [comment]
@wooheaven apologies for the delay! The csv has been added to the examples repo per https://github.com/target/matrixprofile-ts/pull/35. Closing this issue as a result.
