### ISSUE TITLE
Dealing with missing values

### ISSUE THREAD

**Issue by Modestas96** [target/matrixprofile-ts#37]
I tried to use matrix profile to analyse data with missing values, unfortunately I get an empty graph. Is it possible to analyse data with missing values with this implementation? Since in the paper it was stated that matrix profile should result some analysis even with missing data.

**Comment by vanbenschoten** [comment]
@Modestas96 the code should be able to handle missing data, so long as the gaps are small relative to the subsequence length. Can you give some more details about the issue?

**Comment by Modestas96** [comment]
Understood, in my example the gaps are relatively big, so I was wondering if I have to deal with them specifically myself or the algorithm will be able to handle it.  So what happens in my case is that algorithm returns matrix profile with only nan or inf values.

**Comment by vanbenschoten** [comment]
Yeah, in this case you'll probably have to do some custom handling of the gaps. I'd recommend concatenation of the data where possible.

**Comment by previsualconsent** [comment]
I'm curious about how to specify missing data. I used nan's but this broke the results.

```python
import numpy as np
import matplotlib.pyplot as plt
from matrixprofile import *

x = np.linspace(0,100*np.pi,1001)
y = np.sin(x)
mp,ind = matrixProfile.stomp(y,25)
print("No NaNs:", mp[:10], ind[:10])

y[100] = np.nan
mp,ind = matrixProfile.stomp(y,25)
print("One NaN:", mp[:10], ind[:10])```
```
Output
```
No NaNs: [0.8063933  0.69207036 0.70640454 0.54243868 0.47026391 0.3617592
 0.36305626 0.38308637 0.50597634 0.64910376] [200. 201. 422. 423. 804. 566. 806. 807. 228. 229.]
One Nan: [nan nan nan nan nan nan nan nan nan nan] [  3 870   5 870   0 870   0 870   0 870]
```
Is there a different way to handle missing data?

**Comment by tylerwmarrs** [comment]
@vanbenschoten This issue should not be closed. The current stomp implementation does not correctly handle missing values.

**Comment by vanbenschoten** [comment]
@tylerwmarrs agreed

**Comment by vanbenschoten** [comment]
The latest code version (0.0.7) takes care of this issue.
