### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by vanbenschoten** [target/matrixprofile-ts#5]
We've seen interest in making the library compatible with Python 2. We will explore possible avenues, but if you have any thoughts on the subject please reach out.

**Comment by vanbenschoten** [comment]
Upon even more feedback, we'll look into putting Python 2 compatibility on the roadmap.

**Comment by mbarkhau** [comment]
Shameless plug: https://pypi.org/project/lib3to6/

**Comment by mbarkhau** [comment]
Interesting. It seems the tests already pass.

```
$ pytest tests/
============= test session starts ===================
platform linux2 -- Python 2.7.15, pytest-3.5.1, py-1
rootdir: /mnt/c/Users/ManuelBarkhau/Dropbox/projects
inifile:
collected 46 items

tests/test_discords.py .....                   [ 10%] 
tests/test_distanceProfile.py .....            [ 21%]
tests/test_matrixProfile.py ................   [ 56%]
tests/test_order.py ....                       [ 65%]
tests/test_utils.py ................           [100%]

========== 46 passed in 0.35 seconds ================
```

So it may be just the setup.cfg and setup.py that have to be updated.

**Comment by vanbenschoten** [comment]
Awesome! I'll take a look later today and see if we can get things moving. Thanks much for the help!
