### ISSUE TITLE
The link to the CoC in CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by stew** [target/matrixprofile-ts#52]
the CONTRIBUTING.md file refers to a Github Code of Conduct with a URL which is currently 404.

Can we switch this to the Contributor Covenant?:

https://git.target.com/open-source/open-source-project-template/blob/master/templates/.github/CODE_OF_CONDUCT.md

**Comment by vanbenschoten** [comment]
@stew I think that's a good plan. I'm going to review the Code of Conduct in a bit more detail first, but I don't see any issue with this. Thanks for the heads up about the 404!
