### ISSUE TITLE
Readme Section 'Algorithm Comparison' is missleading

### ISSUE THREAD

**Issue by JaKasb** [target/matrixprofile-ts#54]
### Problem 1:
The runtime comparison for short timeseries is useless and missleading.
For short timeseries, the startup-cost and initialization dominates the runtime-complexity.
STOMP reduces the runtime complexity over STAMP, not the startup speed.
#### Solution:
Replace table with plot, made by https://github.com/nschloe/perfplot
Vary the time-series length from 10^1 to 10^5. The larger the better.
#### Bonus:
Include brute-force euclidean distance computation as baseline.
scipy.spatial.distance.euclidean()

### Problem2:
Circular self-reference.
> **SCRIMP++** merges the concepts of STAMP and **SCRIMP++**

**Comment by tylerwmarrs** [comment]
@JaKasb Thank you for raising your concerns. I agree that the plot would allow for a more holistic view. However, your statement about it being useless is a bit over stated. Using the timeit module removes the measurement of the initialization costs when measuring an algorithm. Please see this link for more information about this modue. https://docs.python.org/3/library/timeit.html It is not the most optimal comparison, but an OK baseline. 

If you are willing to add a more comprehensive comparison, that would be awesome and very appreciated.

**Comment by vanbenschoten** [comment]
Closing this issue as Problem 1 has been captured in Issue 57, and Problem 2 has been resolved
