### ISSUE TITLE
Update exclusion zone length from plus or minus m/2 to plus or minus m/4

### ISSUE THREAD

**Issue by vanbenschoten** [target/matrixprofile-ts#6]
Per Zhu et.al we should change the exclusion zone length from m/2 to m/4.

**Comment by tylerwmarrs** [comment]
@vanbenschoten I spent some time making the exclusion zone configurable with a default of 2. Can you think of any unit tests that we need to create? All tests are passing as of now. Please take a peak at my commit here: https://github.com/tylerwmarrs/matrixprofile-ts/commit/6d2f8a4ea1ba90f0d02a1da3d23ea3ccae534328
