### ISSUE TITLE
Implement Annotation Vector

### ISSUE THREAD

**Issue by vanbenschoten** [target/matrixprofile-ts#7]
Adding the AV (Matrix Profile V) will significantly increase usability. This'll probably be the next feature we add.

**Comment by vanbenschoten** [comment]
Implemented with necessary tests

**Comment by peterdhansen** [comment]
According to [Slide 81](https://www.cs.ucr.edu/~eamonn/Matrix_Profile_Tutorial_Part1.pdf)  an annotation vector is applied as:

`CMP_i = MP_i + (1-AV_i)*max(MP)`

The current implementation is `CMP_i = MP_i * AV_i`

**Comment by vanbenschoten** [comment]
@peterdhansen thanks for the callout! I'm going to open an issue addressing this.
