### ISSUE TITLE
Strange behaviour when testing with constant values 

### ISSUE THREAD

**Issue by dvdcoliveira** [target/matrixprofile-ts#71]
Hi, thank you for sharing the Matrix Profile code.It is very helpfull

 I have a time series sample data with a frequency of one point per hour and it work's perfectly with a period of 24, as you can see in image below. 

![Figure_3](https://user-images.githubusercontent.com/53783334/62472564-e9fa8e80-b796-11e9-9808-8742137ede61.png)

the code used was this: 

df_Sample = pd.read_csv('Sample.csv', sep=',')
df_Sample= df_Sample.drop(columns=['Index'])
new_df= df_Sample[:1156]
a = new_df.values.squeeze()
m=24
profile = matrixProfile.stomp(a,m)
new_df['profile'] = np.append(profile[0],np.zeros(m-1)+np.nan)
new_df['profile_index'] = np.append(profile[1], np.zeros(m - 1) + np.nan)
fig, (ax1, ax2) = plt.subplots(2,1,sharex=True,figsize=(15,10))
new_df['Value'].plot(ax=ax1, style='.', title='Sample')
new_df['profile'].plot(ax=ax2, c='r', title='Matrix Profile')
plt.show()

But when I add additional time series data (that is constant) this happens: 
![Figure_1](https://user-images.githubusercontent.com/53783334/62476507-0dc1d280-b79f-11e9-8c9a-f7c09b089d6d.png)

The code is the same but instead of "new_df= df_Sample[:1156]" I defined  "new_df= df_Sample".

I was expecting a different result. It seems that the constant values are destroying all the previous analyses. Is this a bug?

Thanks in advance,

David

[Sample.zip](https://github.com/target/matrixprofile-ts/files/3467819/Sample.zip)

**Comment by vanbenschoten** [comment]
@dvdcoliveira what version of the library are you using? Is it the latest (0.0.8)?

**Comment by dvdcoliveira** [comment]
Hi! @vanbenschoten,

I was using  python version 3.7.1 and matrixprofile-ts version 0.0.6. I updated to 0.0.8 but the problem still persists. 

If I use scrimp++ this does not happen. 

Additional information:
- numpy version 1.15.4
- Windows version 10 Enterprise. 

Many thanks for the support,
David

**Comment by AlexandreRodrigues1** [comment]
Hi,
Found the same issue when appending a constant value zero to the rawdata example.
Solve it by adding a very small noise to the example pattern:
``N = 1046``
``ix = np.arange(N)``
``signal = np.sin(2*np.pi*ix/float(32))*0.01``
``m = 32``
``mp = matrixProfile.stomp(pattern+signal,m)``

Probably it's a problem with the time series z normalization. When I run the matrixprofile with the constant values I get the following errors:
- matrixprofile\utils.py:177: RuntimeWarning: divide by zero encountered in true_divide
- utils.py:200: RuntimeWarning: divide by zero encountered in true_divide
- distanceProfile.py:126: RuntimeWarning: invalid value encountered in sqrt
- matrixProfile.py:249: RuntimeWarning: invalid value encountered in less idsToUpdate = distanceProfile < mp

Hope it helps,
Alex

**Comment by vanbenschoten** [comment]
@AlexandreRodrigues1 thanks much for the contribution! @aouyang1 did you ever figure out a solution to this challenge for go-matrixprofile?

**Comment by AlexandreRodrigues1** [comment]
Thank you to @vanbenschoten and the other contributors too, for the excellent job done in implementing the Matrix Profile algorithms in python :)

**Comment by aouyang1** [comment]
I'll need to test this case as well. I don't believe the golang version handles this nicely either. Hopefully can get back to you all on this in the next few days

**Comment by tylerwmarrs** [comment]
@vanbenschoten This is due to ZNorm logic. The original implementation of MASS and MASS2 optionally allow you to normalize. STOMP implementation actually does not ZNorm for this reason I believe.

**Comment by peterdhansen** [comment]
This is the same as #11

**Comment by tylerwmarrs** [comment]
Closing as issues is same as #11
