### ISSUE TITLE
Support for multivariate time series

### ISSUE THREAD

**Issue by ortegatron** [target/matrixprofile-ts#76]
Hi, 
I was looking for motif discovery on timeseries and find this one. Seems very good, but my data has several variables, it's a multivariate time serie. 
This library doesn't support that, right?
Would it be easy to change the code to support it, or it is just non viable?

Thanks,
MArcelo

**Comment by vanbenschoten** [comment]
Hi Marcelo,
   It's a non-trivial addition, but do-able (we just haven't had the bandwidth to incorporate it yet). We'll hopefully include it in the near future, though you're always welcome to submit your own PR :) In the meantime, the other two libraries supported by the Matrix Profile Foundation (go-matrixprofile (Golang) and tsmp (R)) have multivariate capabilities.

**Comment by ortegatron** [comment]
Sweet, gonna have a look at that ones. Thank you for the quick reply!

**Comment by aouyang1** [comment]
@ortegatron You can also take a look at this paper for multivariate mp. https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf.

**Comment by Sandy4321** [comment]
great code thanks
may you still clarify : 
will it work for multivariate time series as written  in Matrix Profile VI: Meaningful Multidimensional
Motif Discovery 
https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf.
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by vanbenschoten** [comment]
@Sandy4321 unfortunately this library is no longer maintained. I'd recommend you take a look at the Matrix Profile Foundation's new library [here](https://github.com/matrix-profile-foundation/matrixprofile). It's substantially more performant than matrixprofile-ts, and includes a number of additional features (pan-Matrix Profile, Snippets support, etc).

With respect to your original question, the matrixprofile library has an open issue to [add multi-dimensional support in the near future](https://github.com/matrix-profile-foundation/matrixprofile/issues/15). Feel free to add to the discussion there, as well as submit a PR :)
