### ISSUE TITLE
stumpy 

### ISSUE THREAD

**Issue by geoHeil** [target/matrixprofile-ts#77]
Are you affiliated with https://github.com/TDAmeritrade/stumpy? Has anyone compared the performance of stumpy with matrixprofile-ts?

**Comment by vanbenschoten** [comment]
@geoHeil we're not affiliated/competing with Stumpy. We (Matrix Profile Foundation) have different goals in mind, primarily that we focus on broadening usability across as many fields as possible.

**Comment by seanlaw** [comment]
Hi, @vanbenschoten! This is Sean Law, the creator of STUMPY, here. I just wanted to drop in and thank you for bringing more awareness to matrix profile and also to say that I am a fan of your (and your team’s) work. The Matrix Profile Foundation is a wonderful idea for bringing people together into one central place. 

Please feel free to redirect any STUMPY questions my way and we are more than happy to contribute and share in any way that you feel might be helpful to you in achieving your goals! Thank you for all that you do.
