### ISSUE TITLE
Definition and explanation of parameters

### ISSUE THREAD

**Issue by radokotorov** [target/matrixprofile-ts#78]
Can any one provide definitions of the used parameters. The questions are:

(1) How does one determine the samples to be excluded?

 Computes the top k motifs from a matrix profile
    Parameters
    ----------
    ts: time series to used to calculate mp
    mp: tuple, (matrix profile numpy array, matrix profile indices)
    max_motifs: the maximum number of motifs to discover
    ex_zone: the number of samples to exclude and set to Inf on either side of a found motifs
        defaults to m/2
    Returns tuple (motifs, distances)
    motifs: a list of lists of indexes representing the motif starting locations.
    distances: list of minimum distances for each motif
    """

**Comment by tylerwmarrs** [comment]
@radokotorov This specific algorithm requires a domain expert to know what makes sense for exclusion. It is highly dependent on the data. You must consider sampling frequency, window size set to compute the Matrix Profile and other factors specific to the data being analyzed. There currently is not an algorithm that makes or assists you in this process in this library.

**Comment by vanbenschoten** [comment]
Agreed with @tylerwmarrs.

**Comment by radokotorov** [comment]
Ok. But there has to be some logic for setting the exclusion zone. What is it?  

Regards:

Rado Kotorov, Ph.D.
M: 646-761-6444

**Comment by radokotorov** [comment]
What should the domain expert consider? What is the logic?  So let us say a domain expert is doing cardio data sampled at 350. So he knows that the motif length is 350. What does he consider to determine exclusion zone. You can define it in abstract terms, but any domain expert will ask what do i consider to make the choice for exclusion.  

Regards:

Rado Kotorov, Ph.D.
M: 646-761-6444

**Comment by radokotorov** [comment]
What should the domain expert consider? What is the logic?  So let us say a
domain expert is doing cardio data sampled at 350. So he knows that the
motif length is 350. What does he consider to determine exclusion zone. You
can define it in abstract terms, but any domain expert will ask what do i
consider to make the choice for exclusion.

**Comment by vanbenschoten** [comment]
@radokotorov the logic for the exclusion zone is academically defined by Keogh et.al as m/2, where m is your subsequence length. See the first two Matrix Profile papers for reference. The decision to use other values for the exclusion zone is a matter of pure trial and error.

**Comment by radokotorov** [comment]
This is helpful. I think code becomes tremendously more useful when the reasons are provided. Thank you. 

Regards:

Rado Kotorov, Ph.D.
M: 646-761-6444
