### ISSUE TITLE
Question: Finding Shared Motifs for Clustering

### ISSUE THREAD

**Issue by pindapuj** [target/matrixprofile-ts#82]
Thank you for creating matrixprofile-ts! 

I'm trying to cluster a set of time series while using a set of "shared motifs" as "features." Specifically, I have a set of same length time series, where each time series represents a different observation of the same phenomenon. I don't know in advance what type of motifs or behavior can be seen as correct. 

Therefore, I'd like to i) extract a set of k-top motifs that are "shared" across the different samples ii) use these motifs to pull out "features"  from the underlying time series and iii) perform clustering (i was thinking k-means) on the set. 

I was wondering if there was an intuitive way of thinking about this problem. I can find the motifs for a given time series independently by first computing the matrixProfile for each time series, and then finding the motifs (```stomp & motif.motifs```). However, I'm not sure how to get the common set of motifs to then do clustering.  I think having a common set is important b/c  it mitigates the effects of having a "bad observation." 

Clustering over the matrix profile isn't particularly useful and I'm not sure if clustering over the individual "motifs" is as well. 

I'd appreciate any insight into the matter! I'm very new to time series analysis and the matrixProfile work. Thank you!

(Aside: I believe the discord invite link has expired.)

**Comment by tylerwmarrs** [comment]
Thanks for reaching out @pindapuj You are heading down the right track. If it were me, I would probably do something like this for a starting point:

1. Compute matrix profiles for all series of interest.
2. Grab the top K motifs for all matrix profiles.
3. Compute the distance between all motif pairs to see how similar they are. You could use Euclidean distance here. You should end up with a two dimensional matrix of distances for each pair. Scipy module has a Euclidean distance function - https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.euclidean.html
4. You can either write your own clustering algorithm to find clusters or use something from sklearn. When the motifs are clustered, you will need to decide if it makes sense or not.

Be sure to use the same window size and the number of desired motifs.

I hope this helps.

**Comment by tylerwmarrs** [comment]
@pindapuj I am closing this as this is a broad conversation that has been covered in more detail on Discord. Thanks for pointing out the broken invitation link!
