### ISSUE TITLE
Duplicate license files: remove License.md?

### ISSUE THREAD

**Issue by mbrukman** [target/matrixprofile-ts#86]
Looks like there are both a [`LICENSE`][license] as well as a [`License.md`][license.md] file in the repo. The `LICENSE` file is the authoritative full-length Apache license, while the `License.md` is the short-form version, suitable for top-of-file comment header, for example, but not a substitute for the full license.

It would be good to remove `License.md` since it's the short-form version, and it's currently keeping the repo from getting the automatic "Apache 2.0" license badge on the overview page courtesy of [GitHub's automatic license detector][license-badge], due to the presence of 2 license files.

Thanks!

[license]: https://github.com/target/matrixprofile-ts/blob/207aa94cfff143dee824c46c5bad7444a806088c/LICENSE
[license.md]: https://github.com/target/matrixprofile-ts/blob/207aa94cfff143dee824c46c5bad7444a806088c/License.md
[license-badge]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/

**Comment by vanbenschoten** [comment]
@mbrukman thanks for the heads up! @frankiecancino what is Target's stance on just having the LICENSE file? Currently the repo only has the Target copyright in the License.md file: is there an updated version we could use for both?

**Comment by mbrukman** [comment]
_**Disclaimer:** I am not a lawyer and this is not legal advice; this is just my opinion & observations._

Please don't modify the Apache 2.0 `LICENSE` file with a copyright annotation as it will only confuse automated tools (and will not accomplish the automated license chip on the repo overview page).

Also, as soon as you have folks beyond just one company contributing to a project, you would have to change the copyright statement from, e.g., "(c) Target" to "(c) MatrixProfile Authors" or similar, as I've seen in multiple other projects, along with an `AUTHORS` file to specify the authors/copyright holders.

**Comment by vanbenschoten** [comment]
Duplicate License.md file has been removed, so I'm closing this issue.

**Comment by mbrukman** [comment]
Thanks, @vanbenschoten!
