### ISSUE TITLE
Stomp increment is missing

### ISSUE THREAD

**Issue by m-alshaer** [target/matrixprofile-ts#89]
Hello guys,
It is not an issue as much as it is a suggestion of a new important feature.

I noticed that your R package contains the source code for stomp increment (online version), so I am curious to know when are you going to implement this missing algorithm in this python package?

Regards,

**Comment by hmcoservit** [comment]
Any updates on this? STAMPI or STOMPI?

**Comment by vanbenschoten** [comment]
@hmcoservit the Matrix Profile Foundation no longer supports this library, but we're released a much more powerful library here: https://github.com/matrix-profile-foundation/matrixprofile. I know you commented on another issue in this library, so I'd recommend taking a look at our new library and opening new issues over there.
