### ISSUE TITLE
matrixProfile.stomp() gives nan and inf values

### ISSUE THREAD

**Issue by ltbd78** [target/matrixprofile-ts#91]
The following code below gives nan and inf values; am I using this incorrectly?

seconds = np.arange(30)
traffic_light = np.array([0]*15 + [1]*5 + [2]*10)
brake_0 = np.array([0]*15 + [1, 2, 3, 4, 5] + [8, 10, 10, 10, 8, 6, 4, 2, 0, 0])

matrixProfile.stomp(traffic_light, 3)
matrixProfile.stomp(brake_0, 3)

**Comment by vanbenschoten** [comment]
@ltbd78 thanks for the heads up! We're about a week away from a major code release which should fix this problem.

**Comment by nikita-smyrnov** [comment]
@vanbenschoten Any update on when the major code release will be arriving that fixes this bug?

**Comment by vanbenschoten** [comment]
@nikita-smyrnov apologies: the Matrix Profile Foundation is working with Target through a few final details, and we expect that the release will now take place at the end of the month.

**Comment by mpieters93** [comment]
@vanbenschoten could you give us an update on the planned release?

**Comment by vanbenschoten** [comment]
@mpieters93 unfortunately the Matrix Profile Foundation no longer supports this library, and as Target doesn't seem to have any dedicated resources I think it's safe to say that this library is no longer supported overall. That said, the MPF has released a much more powerful Matrix Profile library here: https://github.com/matrix-profile-foundation/matrixprofile . I'd recommend checking it out as we've made many advancements that aren't present in matrixprofile-ts (@ltbd78 for reference, in case this is interesting to you as well).
