### ISSUE TITLE
Annotation Vector file missing from latest matrixprofile-ts build

### ISSUE THREAD

**Issue by nikita-smyrnov** [target/matrixprofile-ts#92]
Apparently the annotation_vector.py file isn't present when using pip to install matrixprofile-ts. Is the version on PyPi outdated? Would like to use the annotation vector feature if possible.

**Comment by vanbenschoten** [comment]
@nikita-smyrnov it looks like the issue is that annotation_vector isn't included in the _init_.py file. You can either build the library straight from the GitHub repo, or make a PR to fix the above _init_.py issue. If you can do that then I'll push to pip.

**Comment by nikita-smyrnov** [comment]
Fixed the init.py. Tested and should be working properly now.

**Comment by frankiecancino** [comment]
Merged the PR. Closing the issue.
