### ISSUE TITLE
ValueError: Length of values does not match length of index

### ISSUE THREAD

**Issue by hn2** [target/matrixprofile-ts#95]
In:

mp = matrixProfile.stomp(pattern,m)
mtfs ,motif_d  = motifs.motifs(pattern, mp, max_motifs=10)

self._set_item(key, value)
value = self._sanitize_column(key, value)
alue = sanitize_index(value, self.index, copy=False)

Any idea how to solve this?

**Comment by vanbenschoten** [comment]
Hi @hn2 - this library is no longer actively maintained. I'd encourage you to try out this Python implementation of the Matrix Profile and raise an issue there if you run into challenges: https://github.com/matrix-profile-foundation/matrixprofile
