### ISSUE TITLE
Pattern Recognition

### ISSUE THREAD

**Issue by AlexiaArtemis** [target/matrixprofile-ts#97]
I would like to use your algorithm but I have one question. My problem is this: I have a query (pattern of interest)  and I would like to find in a time series the patterns that are the closest to the query. Should I use in this case the matrix profile (SCRIMP++) or MASS? 
Thank you!

**Comment by vanbenschoten** [comment]
Hi @AlexiaArtemis ! For your application you'd want to use MASS directly. The Matrix Profile Foundation has the best library for calculating MASS in Python: https://github.com/matrix-profile-foundation/mass-ts. 

As a side note, this library is no longer actively maintained, so I'd encourage you to check out the more advanced Matrix Profile implementation here: https://github.com/matrix-profile-foundation/matrixprofile. There are also libraries in R and Golang.

**Comment by AlexiaArtemis** [comment]
Hi @vanbenschoten! 
Thank you for your fast response!
I would also like to thank your team for the open-source code that you provide.

**Comment by vanbenschoten** [comment]
No problem! Glad you find it useful!

**Comment by AlexiaArtemis** [comment]
Hi, 

In [here ](https://github.com/target/matrixprofile-ts/blob/master/matrixprofile/utils.py) line 159:  the function [mass(query,ts)](https://github.com/target/matrixprofile-ts/blob/6a6f62b72d351f958118a127e81b20469f13b0e7/matrixprofile/utils.py#L159) is this MASS 2.0 ? 

And in line 182, the function [massStomp(query,ts,dot_first,dot_prev,index,mean,std) ](https://github.com/target/matrixprofile-ts/blob/6a6f62b72d351f958118a127e81b20469f13b0e7/matrixprofile/utils.py#L182) is this MASS 3.0? 

Thank you :)

**Comment by vanbenschoten** [comment]
Hi Alexa,
   Unfortunately we don't support matrixprofile-ts anymore, but feel free
to ask us questions about the matrixprofile and mass-ts libraries on their
respective libraries!

**Comment by AlexiaArtemis** [comment]
Ok, then I will use the other libraries. Thank you for your help! :)
