### ISSUE TITLE
Use of 'is' for non-object.

### ISSUE THREAD

**Issue by gbartlet** [target/matrixprofile-ts#99]
Minor, but keeps popping up in tooling we're doing:

In matrixprofile/matrixProfile.py the use of `is` (instead of `==`) to compare `n_threads` to non-object `-1` prompts **SyntaxWarning: "is" with a literal.**

**Comment by vanbenschoten** [comment]
Hi @gbartlet! It might be worth checking out the new "matrixprofile" python library, which has better syntax (and performance, tooling, etc :)
